# ---
# - name: Prepare
#   hosts: all
#   gather_facts: no
#   tasks:
#   - name: Update apt cache (Debian)
#     ansible.builtin.apt:
#       update_cache: yes
#     when: ansible_os_family == "Debian"

#   - name: Update yum cache (RedHat)
#     ansible.builtin.yum:
#       update_cache: yes
#     when: ansible_os_family == "RedHat"

---
- name: Prepare
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Install Ansible Python interpreter
      block:
        - name: Install Python
          ansible.builtin.raw: /bin/apt update && /bin/apt install python3 python3-apt -y
          ignore_errors: true
    - name: Create symbolic link for Python
      ansible.builtin.raw: if [ ! -e /usr/bin/python ]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
    - name: Gathering Facts
      setup:
    - set_fact:
        ansible_python_interpreter: "/usr/bin/python"
